version: '3'
services:
  postgres:
    image: postgres
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    volumes:
      - ./db/data:/var/lib/postgresql/data

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - ./.env
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app
